### PR TITLE
chore: use revive for linting

### PR DESCRIPTION
**Pull request by mhatvan**
## Description

- replace `golint` with `revive` in `Makefile`
- run `make fmt` which updates `statik.go` formatting

## Related issue(s)
Closes https://github.com/zarbchain/zarb-go/issues/234

## Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.

### CODE REVIEW

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@mhatvan Thanks

**Comment by b00f** [comment]
@mhatvan there are some linting issues, could you please fix them as well.

**Comment by mhatvan** [comment]
@b00f Done, you will ned to retrigger the pipeline!

**Comment by b00f** [comment]
Still we have some linting issues, probably because we changed the linting tool: https://github.com/zarbchain/zarb-go/runs/4573799192?check_suite_focus=true#step:5:26

**Comment by mhatvan** [comment]
> Still we have some linting issues, probably because we changed the linting tool: [zarbchain/zarb-go/runs/4573799192?check_suite_focus=true#step:5:26](https://github.com/zarbchain/zarb-go/runs/4573799192?check_suite_focus=true#step:5:26)

The problem is, when running `make fmt` locally, I don't get any errors reported locally.
I fixed the three occurrences the CI check showed. But there are actually more than three.
Any idea why the lint checks work differently for CI and local setup?

**Comment by b00f** [comment]
OK, Let me merge this and I check it locally.

**Pull request merged**
